### ISSUE TITLE
투표 API 개선

### ISSUE THREAD

**Issue by kckc0608** [team-azito/spring-vote-19th#19]
### 🔨 Describe

프론트 요청에 의한 투표 API 개선

### ✅ Tasks

- [ ] 데모데이 투표 시, request body 필드명을 teamName 에서 name 으로 변경
- [ ] 파트장 투표 시, 로그인하지 않았을 때 401 에러가 나는 것을 문서에 명시
- [ ] 데모데이, 파트장 투표시 투표되지 않은 후보에 대해서 0표로 데이터 출력
