### ISSUE TITLE
회원 가입 구현

### ISSUE THREAD

**Issue by leeedohyun** [team-azito/spring-vote-19th#2]
### 📄 Describe

회원 가입을 구현한다.

### ✅ Tasks

- [x] 아이디, 비밀번호, 이메일, 파트, 이름, 팀을 입력받아 회원가입을 한다.
    - [x] 아이디 및 이메일은 중복될 수 없다.
    - [x] 파트는 프론트엔드와 백엔드 중 하나를 선택해야 한다.
    - [x]  팀은 (Azito, BeatBuddy, Buldog, Couplelog, TIG) 중 하나를 선택해야 한다.
